### ISSUE TITLE
Refactor and update existing extended base BLAS packages according to current project conventions

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1152]
This should follow the same process as outlined in https://github.com/stdlib-js/stdlib/issues/788 but for `@stdlib/blas/ext/base/*`.

Packages needing updating:

- [x] `@stdlib/blas/ext/base/dapx`
- [x] `@stdlib/blas/ext/base/dapxsum`
- [x] `@stdlib/blas/ext/base/dapxsumkbn`
- [x] `@stdlib/blas/ext/base/dapxsumkbn2`
- [x] `@stdlib/blas/ext/base/dapxsumors`
- [x] `@stdlib/blas/ext/base/dapxsumpw`
- [x] `@stdlib/blas/ext/base/dasumpw`
- [x] `@stdlib/blas/ext/base/dcusum`
- [x] `@stdlib/blas/ext/base/dcusumkbn`
- [x] `@stdlib/blas/ext/base/dcusumkbn2`
- [x] `@stdlib/blas/ext/base/dcusumors`
- [x] `@stdlib/blas/ext/base/dcusumpw`
- [x] `@stdlib/blas/ext/base/dfill`
- [x] `@stdlib/blas/ext/base/dnanasum`
- [x] `@stdlib/blas/ext/base/dnanasumors`
- [x] `@stdlib/blas/ext/base/dnannsum`
- [x] `@stdlib/blas/ext/base/dnannsumkbn`
- [x] `@stdlib/blas/ext/base/dnannsumkbn2`
- [x] `@stdlib/blas/ext/base/dnannsumors`
- [x] `@stdlib/blas/ext/base/dnannsumpw`
- [x] `@stdlib/blas/ext/base/dnansum`
- [x] `@stdlib/blas/ext/base/dnansumkbn`
- [x] `@stdlib/blas/ext/base/dnansumkbn2`
- [x] `@stdlib/blas/ext/base/dnansumors`
- [x] `@stdlib/blas/ext/base/dnansumpw`
- [x] `@stdlib/blas/ext/base/drev`
- [x] `@stdlib/blas/ext/base/dsapxsum`
- [x] `@stdlib/blas/ext/base/dsapxsumpw`
- [x] `@stdlib/blas/ext/base/dsnannsumors`
- [x] `@stdlib/blas/ext/base/dsnansum`
- [x] `@stdlib/blas/ext/base/dsnansumors`
- [x] `@stdlib/blas/ext/base/dsnansumpw`
- [x] `@stdlib/blas/ext/base/dsort2hp`
- [x] `@stdlib/blas/ext/base/dsort2ins`
- [x] `@stdlib/blas/ext/base/dsort2sh`
- [x] `@stdlib/blas/ext/base/dsorthp`
- [x] `@stdlib/blas/ext/base/dsortins`
- [x] `@stdlib/blas/ext/base/dsortsh`
- [x] `@stdlib/blas/ext/base/dssum`
- [x] `@stdlib/blas/ext/base/dssumors`
- [x] `@stdlib/blas/ext/base/dssumpw`
- [x] `@stdlib/blas/ext/base/dsum`
- [x] `@stdlib/blas/ext/base/dsumkbn`
- [x] `@stdlib/blas/ext/base/dsumkbn2`
- [x] `@stdlib/blas/ext/base/dsumors`
- [x] `@stdlib/blas/ext/base/dsumpw`
- [x] `@stdlib/blas/ext/base/sapx`
- [x] `@stdlib/blas/ext/base/sapxsum`
- [x] `@stdlib/blas/ext/base/sapxsumkbn`
- [x] `@stdlib/blas/ext/base/sapxsumkbn2`
- [x] `@stdlib/blas/ext/base/sapxsumors`
- [x] `@stdlib/blas/ext/base/sapxsumpw`
- [x] `@stdlib/blas/ext/base/sasumpw`
- [x] `@stdlib/blas/ext/base/scusum`
- [x] `@stdlib/blas/ext/base/scusumkbn`
- [x] `@stdlib/blas/ext/base/scusumkbn2`
- [x] `@stdlib/blas/ext/base/scusumors`
- [x] `@stdlib/blas/ext/base/scusumpw`
- [x] `@stdlib/blas/ext/base/sdsapxsum`
- [x] `@stdlib/blas/ext/base/sdsapxsumpw`
- [x] `@stdlib/blas/ext/base/sdsnansum`
- [x] `@stdlib/blas/ext/base/sdsnansumpw`
- [x] `@stdlib/blas/ext/base/sdssum`
- [x] `@stdlib/blas/ext/base/sdssumpw`
- [x] `@stdlib/blas/ext/base/sfill`
- [x] `@stdlib/blas/ext/base/snansum`
- [x] `@stdlib/blas/ext/base/snansumkbn`
- [x] `@stdlib/blas/ext/base/snansumkbn2`
- [x] `@stdlib/blas/ext/base/snansumors`
- [x] `@stdlib/blas/ext/base/snansumpw`
- [x] `@stdlib/blas/ext/base/srev`
- [x] `@stdlib/blas/ext/base/ssort2hp`
- [x] `@stdlib/blas/ext/base/ssort2ins`
- [x] `@stdlib/blas/ext/base/ssort2sh`
- [x] `@stdlib/blas/ext/base/ssorthp`
- [x] `@stdlib/blas/ext/base/ssortins`
- [x] `@stdlib/blas/ext/base/ssortsh`
- [x] `@stdlib/blas/ext/base/ssum`
- [x] `@stdlib/blas/ext/base/ssumkbn`
- [x] `@stdlib/blas/ext/base/ssumkbn2`
- [x] `@stdlib/blas/ext/base/ssumors`
- [x] `@stdlib/blas/ext/base/ssumpw`

**Comment by kailash360** [comment]
@kgryte 

Can I work on this issue?

**Comment by kgryte** [comment]
@kailash360 Sure. How about you start with [`@stdlib/blas/ext/base/dapx`](https://github.com/stdlib-js/stdlib/tree/ad6930b1c7c20277297f57b9477744c08baa022b/lib/node_modules/%40stdlib/blas/ext/base/dapx).

**Comment by kailash360** [comment]
working on [@stdlib/blas/ext/base/dapx](https://github.com/stdlib-js/stdlib/tree/ad6930b1c7c20277297f57b9477744c08baa022b/lib/node_modules/%40stdlib/blas/ext/base/dapx).

**Comment by kgryte** [comment]
@kailash360 You might find the various linked commits and PRs in the upstream issue to be good references. For example, https://github.com/stdlib-js/stdlib/commit/91a2badac012efea2c027c515a1c60da7a8797cf, which makes updates to a single-precision API.

**Comment by kgryte** [comment]
...and https://github.com/stdlib-js/stdlib/commit/3c82fe7b6c0f9fd6ef02c86d6e2024d708ac8c14, which makes updates to a complex number API.

**Comment by rxbryan** [comment]
Hi @kgryte I have started work on [@stdlib/blas/ext/base/sapx](https://github.com/stdlib-js/stdlib/tree/ad6930b1c7c20277297f57b9477744c08baa022b/lib/node_modules/%40stdlib/blas/ext/base/sapx).

**Comment by kgryte** [comment]
@kailash360 Are you still planning to work on `dapx`? If so, can you respond on https://github.com/stdlib-js/stdlib/issues/1464?

**Comment by GittyHarsha** [comment]
Hi @kgryte, after working on a few good first issues, I now feel confident and will work on ``blas/ext/base/dsnannsumors`

**Comment by gururaj1512** [comment]
Is this issue resolved completely? If not which packages are yet to be refactored

**Comment by Planeshifter** [comment]
@gururaj1512 Double-checked and looks llke almost all are completed. `@stdlib/blas/ext/base/snansumkbn2` is the only one that still has to be updated as far as I can tell.

**Comment by saurabhraghuvanshii** [comment]
I think this has been done   `@stdlib/blas/ext/base/snansumkbn2`  , so why it is not check.

**Comment by 0PrashantYadav0** [comment]
I think all the issues have been resolved to this tracking issue must be closed as well.

**Comment by Planeshifter** [comment]
Thanks for the heads-up, @saurabhraghuvanshii and @0PrashantYadav0! Closing now...
