### ISSUE TITLE
[RFC]: add C implementation for `math/base/special/fast/*` (Tracking Issue)

### ISSUE THREAD

**Issue by gunjjoshi** [stdlib-js/stdlib#1917]
### Description

This RFC proposes adding C implementations for the following packages :

- [x]  abs - https://github.com/stdlib-js/stdlib/pull/1894
- [x]  acosh - https://github.com/stdlib-js/stdlib/pull/1897
- [x]  alpha-max-plus-beta-min - https://github.com/stdlib-js/stdlib/pull/1947
- [x]  asinh - https://github.com/stdlib-js/stdlib/pull/1908
- [x]  atanh - https://github.com/stdlib-js/stdlib/pull/1909
- [x]  hypot - https://github.com/stdlib-js/stdlib/pull/1910
- [x]  max - https://github.com/stdlib-js/stdlib/pull/1912
- [x]  min - https://github.com/stdlib-js/stdlib/pull/1913
- [x]  pow-int - https://github.com/stdlib-js/stdlib/pull/1919
- [x]  uint32-log2 - https://github.com/stdlib-js/stdlib/pull/1946
- [x]  uint32-sqrt - https://github.com/stdlib-js/stdlib/pull/1960

### Related Issues

Related issues #649.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by gunjjoshi** [comment]
This is a tracking issue for C implementations of `math/base/special/fast` packages.

**Comment by Pranavchiku** [comment]
Awesome, thanks @gunjjoshi! I'll expect this to get done quickly.

Edit: If there are no blockers for `alpha-max-plus-beta-min`, `uint32-log2`,`uint32-sqrt` please feel free to open PRs and wrap this up.

**Comment by gunjjoshi** [comment]
Sure @Pranavchiku,, as there are no blockers on the remaining ones, I'll look forward to wrap this up super quick !

**Comment by Pranavchiku** [comment]
I think this was close by mistake, reopening

**Comment by USERSATOSHI** [comment]
@gunjjoshi Hi,
can you add [feat(math): c implementation of alpha-max-plus-beta-min](https://github.com/stdlib-js/stdlib/pull/1947) to the track list

##### for copying the link directly
```bash
[feat(math): c implementation of alpha-max-plus-beta-min](https://github.com/stdlib-js/stdlib/pull/1947)
```

**Comment by gunjjoshi** [comment]
Done @USERSATOSHI ! Thanks.

**Comment by USERSATOSHI** [comment]
> Done @USERSATOSHI ! Thanks.

I also found this pr for [feat: add C implementation for math/base/special/fast/uint32-log2](https://github.com/stdlib-js/stdlib/pull/1946)

##### for copying the link format
```
[feat: add C implementation for math/base/special/fast/uint32-log2](https://github.com/stdlib-js/stdlib/pull/1946)
```

**Comment by gunjjoshi** [comment]
As all tasks are completed, we can close this now.

**Comment by Pranavchiku** [comment]
Brilliant, nice job!
