### ISSUE TITLE
[RFC]: Add BLAS bindings and implementations for linear algebra (tracking issue)

### ISSUE THREAD

**Issue by aman-095** [stdlib-js/stdlib#2039]
### Description

This RFC proposes adding BLAS routines. The purpose of this issue is to serve as a tracking issue for adding BLAS routines.

# Implementation Status for BLAS Routines

### Single Precision

- [ ] SROTG
    - [x] JavaScript
    - [ ] C: https://github.com/stdlib-js/stdlib/pull/4762 : https://github.com/stdlib-js/stdlib/pull/987
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] SROTMG
    - [ ] JavaScript: https://github.com/stdlib-js/stdlib/pull/4710
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [x] SROT
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] SROTM
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] SSWAP
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] SSCAL
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] SCOPY
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] SAXPY
    - [x] JavaScript
    - [x] C/Fortran
- [x] SDOT
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] SDSDOT
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] SNRM2
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] SCNRM2
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] SASUM
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] ISAMAX
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly

### Double Precision

- [ ] DROTG
    - [x] JavaScript
    - [ ] C : https://github.com/stdlib-js/stdlib/pull/2264
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DROTMG
    - [ ] JavaScript : https://github.com/stdlib-js/stdlib/pull/5022
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [x] DROT
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] DROTM
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] DSWAP
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] DSCAL
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] DCOPY
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] DAXPY
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] DDOT
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] DSDOT
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] DNRM2
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] DZNRM2
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] DASUM
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] IDAMAX
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly

### Complex Single

- [ ] CROTG
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [x] CSROT
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] CSWAP
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] CSCAL
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [ ] CSSCAL
    - [x] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [x] CCOPY
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [ ] CAXPY
    - [x] JavaScript
    - [x] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CDOTU
    - [ ] JavaScript : https://github.com/stdlib-js/stdlib/pull/4773
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CDOTC
    - [ ] JavaScript : https://github.com/stdlib-js/stdlib/pull/4752
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [x] SCASUM
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [ ] ICAMAX
    - [ ] JavaScript : https://github.com/stdlib-js/stdlib/pull/5068
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly

### Complex Double 

- [ ] ZROTG
    - [ ] JavaScript : https://github.com/stdlib-js/stdlib/pull/6697
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [x] ZDROT
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] ZSWAP
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [x] ZSCAL
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [ ] WebAssembly : https://github.com/stdlib-js/stdlib/pull/6810
- [ ] ZDSCAL
    - [x] JavaScript
    - [x] C : https://github.com/stdlib-js/stdlib/pull/7086
    - [x] Fortran
    - [ ] WebAssembly
- [x] ZCOPY
    - [x] JavaScript
    - [x] C
    - [x] Fortran
    - [x] WebAssembly
- [ ] ZAXPY
    - [x] JavaScript
    - [x] C : https://github.com/stdlib-js/stdlib/pull/7594
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZDOTU
    - [ ] JavaScript : https://github.com/stdlib-js/stdlib/pull/6613
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZDOTC
    - [ ] JavaScript : https://github.com/stdlib-js/stdlib/pull/6847
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DZASUM
    - [ ] JavaScript : https://github.com/stdlib-js/stdlib/pull/4697
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] IZAMAX
    - [ ] JavaScript : https://github.com/stdlib-js/stdlib/pull/4787
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly

### Single Precision

- [ ] SGEMV
    - [x] JavaScript
    - [x] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] SGBMV
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/5928
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] SSYMV
    - [x] JavaScript  : https://github.com/stdlib-js/stdlib/pull/2843 (refactoring)
    - [ ] C  : https://github.com/stdlib-js/stdlib/pull/7142
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] SSBMV
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/6666
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] SSPMV
    - [x] JavaScript  : https://github.com/stdlib-js/stdlib/pull/2839 ( refactoring )
    - [ ] C  : https://github.com/stdlib-js/stdlib/pull/7141
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] STRMV
    - [x] JavaScript
    - [ ] C  : https://github.com/stdlib-js/stdlib/pull/7017
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] STBMV
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/6878
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] STPMV
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/2825
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] STRSV
    - [x] JavaScript
    - [ ] C  : https://github.com/stdlib-js/stdlib/pull/7154
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] STBSV
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/6709
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] STPSV
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/2822
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] SGER
    - [x] JavaScript
    - [x] C
    - [x] Fortran: Not working due to dep resolution
    - [ ] WebAssembly
- [ ] SSYR
    - [x] JavaScript
    - [x] C 
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] SSPR
    - [x] JavaScript
    - [x] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] SSYR2
    - [x] JavaScript
    - [x] C  : https://github.com/stdlib-js/stdlib/pull/2880
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] SSPR2
    - [ ] JavaScript
    - [ ] C  : https://github.com/stdlib-js/stdlib/pull/2801
    - [ ] Fortran
    - [ ] WebAssembly

### Double Precision

- [ ] DGEMV
    - [x] JavaScript
    - [x] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DGBMV
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/6121
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DSYMV
    - [x] JavaScript  : https://github.com/stdlib-js/stdlib/pull/2844
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DSBMV
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/6650
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DSPMV
    - [x] JavaScript  : https://github.com/stdlib-js/stdlib/pull/2840
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DTRMV
    - [x] JavaScript 
    - [ ] C  : https://github.com/stdlib-js/stdlib/pull/7016
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DTBMV
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/6862
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DTPMV
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/2827
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DTRSV
    - [x] JavaScript
    - [ ] C  : https://github.com/stdlib-js/stdlib/pull/7157
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DTBSV
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/6707
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DTPSV
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/2823
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DGER
    - [x] JavaScript
    - [x] C
    - [x] Fortran: Not working due to dep resolution
    - [ ] WebAssembly
- [ ] DSYR
    - [x] JavaScript
    - [x] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DSPR
    - [x] JavaScript
    - [ ] C  : https://github.com/stdlib-js/stdlib/pull/6580
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DSYR2
    - [x] JavaScript
    - [x] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DSPR2
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/2803
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly

### Complex Single

- [ ] CGEMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CGBMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CHEMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CHBMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CHPMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CTRMV
    - [ ] JavaScript https://github.com/stdlib-js/stdlib/pull/7497
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CTBMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CTPMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CTRSV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CTBSV
    - [ ] JavaScript
    - [ ] C/Fortran
- [ ] CTPSV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CGERU
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CGERC
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CHER
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7088
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CHPR
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CHER2
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7206
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CHPR2
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly

### Complex Double

- [ ] ZGEMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZGBMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZHEMV
    - [ ] JavaScript
    - [ ] C/Fortran
- [ ] ZHBMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZHPMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZTRMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZTBMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZTPMV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZTRSV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZTBSV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZTPSV
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZGERU
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZGERC
    - [ ] JavaScript
    - [ ] C/Fortran
- [ ] ZHER
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7119
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZHPR
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZHER2
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7251
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZHPR2
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly

### Single Precision

- [ ] SGEMM
    - [x] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] SSYMM
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7385
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] SSYRK
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7411
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] SSYR2K
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7462
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] STRMM
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7343
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] STRSM
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7021
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly

### Double Precision

- [ ] DGEMM
    - [x] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DSYMM
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7382
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DSYRK
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7412
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DSYR2K
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7437
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DTRMM
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7366
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] DTRSM
    - [ ] JavaScript  : https://github.com/stdlib-js/stdlib/pull/7359
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly

### Complex Single

- [ ] CGEMM
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CSYMM
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CHEMM
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CSYRK
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CHERK
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CSYR2K
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CHER2K
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CTRMM
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] CTRSM
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly

### Complex Double

- [ ] ZGEMM
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZSYMM
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZHEMM
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZSYRK
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZHERK
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZSYR2K
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZHER2K
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZTRMM
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly
- [ ] ZTRSM
    - [ ] JavaScript
    - [ ] C
    - [ ] Fortran
    - [ ] WebAssembly

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by performant23** [comment]
Hello, thanks @aman-095 for adding this tracker. So, I just wanted to let you know that I am working on `ZSWAP` just so we don't end up working on the same package :) 

Apologies for not adding an issue for the same earlier, thanks!

**Comment by aman-095** [comment]
Working on idamax and isamax level 1 routines.

**Comment by performant23** [comment]
Working on csscal (L1)

**Comment by kgryte** [comment]
@performant23 That one is already being worked on in https://github.com/stdlib-js/stdlib/pull/2104.

**Comment by kgryte** [comment]
@performant23 Maybe try `dznrm2`?

**Comment by performant23** [comment]
Oh, hey! I think `csscal` is different right? In `cscal` we have a complex scalar and in `csscal` we have a real scalar if I remember correctly.

**Comment by kgryte** [comment]
Ah, you're right. That one should be straightforward.

**Comment by performant23** [comment]
Hi @kgryte, we would need a generic interface to perform Givens rotation with vectors of other data types like integers, right? If so, I'd like to work on such an interface i.e. `grot` to get an idea of how generic `g*` interfaces are sampled from their equivalent `d*` implementations and also since we have implementations for those available for this package (JS implementation for `drot` is reviewed), this should be good to go!

**Comment by aman-095** [comment]
Working on Level 1 routine `drotm`

**Comment by kgryte** [comment]
@performant23 Yes, go for it. The one thing you need to do is ensure accessor array support. See `gcopy` and `gswap` for an idea.

**Comment by Vinit-Pandit** [comment]
For `SROTMG`  do we need to perform the scaling check as done in the Lapack Fortren [implementation](https://www.netlib.org/lapack/explore-html/d3/dd5/group__rotmg_ga4e2582ebf7f445a7628954183c4cce30.html#ga4e2582ebf7f445a7628954183c4cce30) . 
It seems that the SciPy implementation doesn’t include this step.

**Comment by Vinit-Pandit** [comment]
`SROTMG` in SciPy only returning the transformation matrix and flag .

**Comment by ShabiShett07** [comment]
I have given a try to create a `SROTMG` package please do check it!

**Comment by ShabiShett07** [comment]
There is a PR #2518 for dtrsm, I am mentioning this PR so that there is no confusion about duplicate PRs.

**Comment by Hell1213** [comment]
@kgryte @aman-095 @Vinit-Pandit hey guys 
I'm Rajat Yadav a fullStack dev  and a newcomer here i want to know how this RFC issues thing work like should i go with pick to build any one which is unmarked or this RFC has been finished no need to work on this as I saw accepted label there ,pls kindly tell how should i pick a issue or a feature to work on bcs I'm good at my stack mern,python,typescript. I'm eager to contribute in stdlib pls guide me a bit !!

**Comment by aryan7071** [comment]
hey @kgryte  i wanted to work on this issue but i first want to know if this above issue is up to date or not?

**Comment by DivitJain26** [comment]
Hey @kgryte
I found a few routines that aren't currently listed. Thought it'd be useful to flag them here so we can decide whether to add them to the RFC.

### Level 1 Missing Routines
- `SCSUM1`
- `DZSUM1` 
- `ICMAX1`
- `IZMAX1` 

### Level 2 Missing Routines
- `CSYMV`
- `ZSYMV`
- `CSYR`
- `ZSYR`
- `CSPMV`
- `ZSPMV`
- `CSPR`
- `ZSPR`

### Level 3 Missing Routines
- `SGEMMTR`
- `DGEMMTR`
- `CGEMMTR`
- `ZGEMMTR`

Reference
- https://www.netlib.org/lapack/explore-html/de/d6a/group__blas__top.html
