### ISSUE TITLE
[RFC]: Add/Update package for `BooleanArray` support (tracking issue)

### ISSUE THREAD

**Issue by Jaysukh-409** [stdlib-js/stdlib#2304]
### Description

This RFC proposes add or update all packages that needs to be changed in order to add `BooleanArray` support to Stdlib. The purpose of this issue is to serve as a tracking issue for update or add packages.

### Packages need to added:

- [x] `@stdlib/assert/is-booleanarray`
- [x] `@stdlib/strided/base/reinterpret-boolean`
- [x]  `@stdlib/array/base/assert/is-booleanarray`
- [x]   `@stdlib/assert/is-same-booleanarray`

### Packages need to updated:

- [x] `@stdlib/array/dtypes`
- [x] `@stdlib/array/dtype`
- [x] `@stdlib/array/bool` - add methods of `BooleanArray` and `repl.txt`
- [x] `@stdlib/array/min-dtype`
- [x] `@stdlib/array/ctors`
- [x] `@stdlib/array/convert`
- [x] `@stdlib/array/convert-same` - update tests and benchmarks
- [x] `@stdlib/array/defaults`
- [x] `@stdlib/array/docs/types`
- [x] `@stdlib/array/empty`
- [x] `@stdlib/array/empty-like`
- [x] `@stdlib/array/filled`
- [x] `@stdlib/array/filled-by`
- [x] `@stdlib/array/from-scalar` - add tests
- [x] `@stdlib/array/full`
- [x] `@stdlib/array/full-like`
- [x] `@stdlib/array/mostly-safe-casts`
- [x] `@stdlib/array/next-dtype`
- [x] `@stdlib/array/pool`
- [x] `@stdlib/array/promotion-rules`
- [x] `@stdlib/array/safe-casts`
- [x] `@stdlib/array/same-kind-casts`
- [x] `@stdlib/array/reviver`
- [x] `@stdlib/array/to-json`
- [x] `@stdlib/array/typed-ctors`
- [x] `@stdlib/array/typed-dtypes`
- [x] `@stdlib/array/typed`
- [x] `@stdlib/array/base/any`
- [x] `@stdlib/array/base/assert/has-same-values`
- [x] `@stdlib/array/base/count-falsy`
- [x] `@stdlib/array/base/count-truthy`
- [x] `@stdlib/array/base/count-same-value`
- [x] `@stdlib/array/base/count-same-value-zero`
- [x] `@stdlib/array/base/cuany`
- [x] `@stdlib/array/base/cuevery`
- [x] `@stdlib/array/base/every`
- [x] `@stdlib/array/base/mskfilter`
- [x] `@stdlib/array/base/mskreject`
- [x] `@stdlib/array/base/none`
- [x] `@stdlib/array/base/take`

### Related Issues

None

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
@Jaysukh-409 Looks like we also need to update various packages in `@stdlib/array/base/assert/*` to support boolean data types. Should add those packages to the list, as well.

**Comment by kgryte** [comment]
The list should also include:

- typed-dtypes
- typed
- promotion-rules
- next-dtype
- safe-casts
- same-kind-casts
- from-scalar (tests)
- pool
- to-json

**Comment by kgryte** [comment]
@Jaysukh-409 I updated the OP with additional `array/base/*` packages which need to be updated to specially handle BooleanArrays. I've added boolean array support to [`@stdlib/array/base/put`](https://github.com/stdlib-js/stdlib/blob/c8118827f71ca602ccfea2721df03afbbd3857e5/lib/node_modules/%40stdlib/array/base/put/lib/main.js) and the updates to the various "base" packages will be along similar lines. Namely, where possible, reinterpreting a boolean array to allow more efficient element access.

**Comment by kgryte** [comment]
As all tasks in this tracking issue are now completed, I'll go ahead and close. Thanks, @Jaysukh-409!
