### ISSUE TITLE
[RFC]: Add/Update package of strided namespace for BooleanArray support (tracking issue)

### ISSUE THREAD

**Issue by Jaysukh-409** [stdlib-js/stdlib#2500]
### Description

This RFC proposes add or update all packages of strided namespace that needs to be changed in order to add BooleanArray support to Stdlib. The purpose of this issue is to serve as a tracking issue for update or add packages.

### Packages need to added:

- [x] `@stdlib/strided/base/reinterpret-boolean` 
 
### Prerequisites of `ndarray` namespace:

- [x] `@stdlib/ndarray/base/dtype-char`
- [x] `@stdlib/ndarray/base/dtype-desc`
- [x] `@stdlib/ndarray/base/dtype2c`
- [x] `@stdlib/ndarray/base/char2dtype`
- [x] `@stdlib/ndarray/safe-casts`
- [x] `@stdlib/ndarray/promotion-rules`

### Packages need to updated:

- [x] `@stdlib/strided/dtypes`
- [x] `@stdlib/strided/base/nullary`
- [x] `@stdlib/strided/base/nullary-addon-dispatch`
- [x] `@stdlib/strided/base/unary`
- [x] `@stdlib/strided/base/unary-addon-dispatch`
- [x] `@stdlib/strided/base/mskunary`
- [x] `@stdlib/strided/base/mskunary-addon-dispatch`
- [x] `@stdlib/strided/base/binary`
- [x] `@stdlib/strided/base/binary-addon-dispatch`

### Related Issues

None

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
All tasks have now been completed. Closing...
