### ISSUE TITLE
[RFC]: Add/Update package of ndarray namespace for BooleanArray support (tracking issue)

### ISSUE THREAD

**Issue by Jaysukh-409** [stdlib-js/stdlib#2547]
### Description

This RFC proposes add or update all packages of ndarray namespace that needs to be changed in order to add BooleanArray support to Stdlib. The purpose of this issue is to serve as a tracking issue for update or add packages.

### Packages need to be added:

- [x] `@stdlib/ndarray/base/assert/is-boolean-data-type`

### Packages need to be updated:

- [x] `@stdlib/ndarray/base/assign`
- [x] `@stdlib/ndarray/base/buffer-ctors`
- [x] `@stdlib/ndarray/base/buffer-dtype` 
- [x] `@stdlib/ndarray/base/buffer` -> update docs
- [x] `@stdlib/ndarray/base/nullary`
- [x] `@stdlib/ndarray/base/unary`
- [x] `@stdlib/ndarray/dtypes`
- [x] `@stdlib/ndarray/defaults`
- [x] `@stdlib/ndarray/from-scalar`
- [x] `@stdlib/ndarray/min-dtype`
- [x] `@stdlib/ndarray/mostly-safe-casts`
- [x] `@stdlib/ndarray/next-dtype`
- [x] `@stdlib/ndarray/same-kind-casts` 
- [x] `@stdlib/ndarray/base/zeros`, `@stdlib/ndarray/base/empty`, `@stdlib/ndarray/base/zeros-like`, `@stdlib/ndarray/base/empty-like` -> update tests 
- [x] `@stdlib/ndarray/zeros`, `@stdlib/ndarray/empty`, `@stdlib/ndarray/zeros-like`, `@stdlib/ndarray/empty-like` -> update tests 

### Related Issues

None

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
@Jaysukh-409 As I believe everything in this tracking issue has now been completed, I will go ahead and close this issue.
