### ISSUE TITLE
[RFC]: Add C implementations to base special math functions (tracking issue)

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#649]
### Description

This RFC proposes adding C implementations to all base special math functions. The purpose of this issue is to serve as a tracking issue for adding C implementations.

### Packages

- [x] abs
- [x] abs2
- [x] abs2f
- [x] absf
- [x] acos
- [x] acosf
- [x] acosd
- [x] acosdf
- [x] acosh
- [ ] acoshf
- [x] acot
- [x] acotf
- [x] acotd
- [x] acotdf
- [x] acoth
- [ ] acothf
- [x] acovercos
- [x] acovercosf
- [x] acoversin
- [x] acoversinf
- [x] acsc
- [x] acscf
- [x] acscd
- [x] acscdf
- [x] acsch
- [ ] acschf
- [x] ahavercos
- [x] ahavercosf
- [x] ahaversin
- [x] ahaversinf
- [x] asec
- [x] asecf
- [x] asecd
- [x] asecdf
- [x] asech
- [ ] asechf
- [x] asin
- [x] asinf
- [x] asind
- [x] asindf
- [x] asinf
- [x] asinh
- [ ] asinhf
- [x] atan
- [x] atanf
- [x] atan2
- [x] atan2f
- [x] atand
- [x] atandf
- [x] atanh
- [ ] atanhf
- [x] avercos
- [x] avercosf
- [x] aversin
- [x] aversinf
- [x] bernoulli
- [x] bernoullif
- [x] besselj0
- [ ] besselj0f
- [x] besselj1
- [ ] besselj1f
- [x] bessely0
- [ ] bessely0f
- [x] bessely1
- [ ] bessely1f
- [x] beta
- [ ] betaf
- [ ] betainc
- [ ] betaincf
- [ ] betaincinv
- [ ] betaincinvf
- [x] betaln
- [ ] betalnf
- [x] binet
- [ ] binetf
- [x] binomcoef
- [x] binomcoeff
- [x] binomcoefln
- [ ] binomcoeflnf
- [x] boxcox
- [ ] boxcoxf
- [x] boxcox1p
- [ ] boxcox1pf
- [x] boxcox1pinv
- [ ] boxcox1pinvf
- [x] boxcoxinv
- [ ] boxcoxinvf
- [x] cabs
- [x] cabs2
- [x] cabs2f
- [x] cabsf
- [x] cbrt
- [x] cbrtf
- [x] cceil
- [x] cceilf
- [x] cceiln
- [ ] cceilnf
- [x] ccis
- [ ] ccisf
- [x] ceil
- [x] ceil10
- [ ] ceil10f
- [x] ceil2
- [ ] ceil2f
- [x] ceilb
- [ ] ceilbf
- [x] ceilf
- [x] ceiln
- [ ] ceilnf
- [x] ceilsd
- [ ] ceilsdf
- [x] cexp
- [ ] cexpf
- [x] cflipsign
- [x] cflipsignf
- [x] cfloor
- [x] cfloorf
- [x] cfloorn
- [ ] cfloornf
- [x] cidentity
- [x] cidentityf
- [x] cinv
- [x] cinvf
- [x] clamp
- [x] clampf
- [x] copysign
- [x] copysignf
- [x] cos
- [x] cosf
- [x] cosd
- [x] cosdf
- [x] cosh
- [ ] coshf
- [x] cosm1
- [x] cosm1f
- [x] cospi
- [x] cospif
- [x] cot
- [x] cotf
- [x] cotd
- [x] cotdf
- [x] coth
- [ ] cothf
- [x] covercos
- [x] covercosf
- [x] coversin
- [x] coversinf
- [x] cphase
- [x] cphasef
- [x] cpolar
- [x] cpolarf
- [x] cround
- [x] croundf
- [x] croundn
- [ ] croundnf
- [x] csc
- [x] cscf
- [x] cscd
- [x] cscdf
- [x] csch
- [ ] cschf
- [x] csignum
- [x] csignumf
- [x] deg2rad
- [x] deg2radf
- [x] digamma
- [ ] digammaf
- [x] dirac-delta
- [x] dirac-deltaf
- [x] dirichlet-eta
- [ ] dirichlet-etaf
- [x] ellipe
- [ ] ellipef
- [x] ellipj
- [ ] ellipjf
- [x] ellipk
- [ ] ellipkf
- [x] erf
- [ ] erff
- [x] erfc
- [ ] erfcf
- [x] erfcinv
- [ ] erfcinvf
- [x] erfcx
- [ ] erfcxf
- [x] erfinv
- [ ] erfinvf
- [x] exp
- [ ] expf
- [x] exp10
- [ ] exp10f
- [x] exp2
- [ ] exp2f
- [x] expit
- [ ] expitf
- [x] expm1
- [ ] expm1f
- [x] expm1rel
- [ ] expm1relf
- [x] factorial
- [ ] factorialf
- [x] factorial2
- [x] factorial2f
- [x] factorialln
- [x] factoriallnf
- [x] falling-factorial
- [ ] falling-factorialf
- [x] fast/\*
- [x] fibonacci
- [x] fibonaccif
- [x] fibonacci-index
- [x] fibonacci-indexf
- [x] flipsign
- [x] flipsignf
- [x] floor
- [x] floor10
- [ ] floor10f
- [x] floor2
- [ ] floor2f
- [x] floorb
- [ ] floorbf
- [x] floorf
- [x] floorn
- [ ] floornf
- [x] floorsd
- [ ] floorsdf
- [x] fmod
- [x] fmodf
- [x] fresnel
- [ ] fresnelf
- [x] fresnelc
- [ ] fresnelcf
- [x] fresnels
- [ ] fresnelsf
- [x] frexp
- [x] frexpf
- [x] gamma
- [ ] gammaf
- [x] gamma-delta-ratio
- [ ] gamma-delta-ratiof
- [x] gamma-lanczos-sum
- [ ] gamma-lanczos-sumf
- [x] gamma-lanczos-sum-expg-scaled
- [x] gamma-lanczos-sum-expg-scaledf
- [x] gamma1pm1
- [ ] gamma1pm1f
- [x] gammainc
- [ ] gammaincf
- [ ] gammaincinv
- [ ] gammaincinvf
- [x] gammaln
- [ ] gammalnf
- [x] gammasgn
- [x] gammasgnf
- [x] gcd
- [x] gcdf
- [x] hacovercos
- [x] hacovercosf
- [x] hacoversin
- [x] hacoversinf
- [x] havercos
- [x] havercosf
- [x] haversin
- [x] haversinf
- [ ] heaviside
- [x] heavisidef
- [x] hypot
- [x] hypotf
- [x] identity
- [x] identityf
- [x] inv
- [x] invf
- [ ] kernel-betainc
- [ ] kernel-betaincf
- [ ] kernel-betaincinv
- [ ] kernel-betaincinvf
- [x] kernel-cos
- [x] kernel-cosf
- [x] kernel-sin
- [x] kernel-sinf
- [x] kernel-tan
- [x] kernel-tanf
- [x] kronecker-delta
- [x] kronecker-deltaf
- [x] labs
- [x] lcm
- [x] lcmf
- [x] ldexp
- [x] ldexpf
- [x] ln
- [x] lnf
- [x] log
- [x] logf
- [x] log10
- [ ] log10f
- [x] log1mexp
- [ ] log1mexpf
- [x] log1p
- [x] log1pf
- [x] log1pexp
- [ ] log1pexpf
- [x] log1pmx
- [ ] log1pmxf
- [x] log2
- [ ] log2f
- [x] logaddexp
- [ ] logaddexpf
- [x] logit
- [x] logitf
- [x] lucas
- [x] lucasf
- [x] max
- [x] maxf
- [x] maxabs
- [x] maxabsf
- [ ] ~~maxabsn~~
- [ ] ~~maxn~~
- [x] min
- [x] minf
- [x] minabs
- [x] minabsf
- [ ] ~~minabsn~~
- [x] minmax
- [x] minmaxf
- [x] minmaxabs
- [x] minmaxabsf
- [ ] ~~minmaxabsn~~
- [ ] ~~minmaxn~~
- [ ] ~~minn~~
- [x] modf
- [x] modff
- [x] nanmax
- [x] nanmaxf
- [x] nanmin
- [x] nanminf
- [x] negafibonacci
- [x] negafibonaccif
- [x] negalucas
- [x] negalucasf
- [x] nonfibonacci
- [x] nonfibonaccif
- [x] pdiff
- [x] pdifff
- [ ] polygamma
- [ ] polygammaf
- [x] pow
- [x] powf
- [x] powm1
- [ ] powm1f
- [x] rad2deg
- [x] rad2degf
- [x] ramp
- [x] rampf
- [x] rcbrt
- [x] rcbrtf
- [x] rempio2
- [x] rempio2f
- [x] riemann-zeta
- [ ] riemann-zetaf
- [x] rising-factorial
- [ ] rising-factorialf
- [x] round
- [x] roundf
- [x] round10
- [ ] round10f
- [x] round2
- [ ] round2f
- [x] roundb
- [ ] roundbf
- [x] roundn
- [ ] roundnf
- [x] roundsd
- [ ] roundsdf
- [x] rsqrt
- [x] rsqrtf
- [x] sec
- [x] secd
- [x] secdf
- [x] secf
- [ ] sici
- [ ] sicif
- [x] signum
- [x] signumf
- [x] sin
- [x] sinf
- [x] sinc
- [x] sincf
- [x] sincos
- [x] sincosd
- [ ] sincosdf
- [x] sincosf
- [x] sincospi
- [ ] sincospif
- [x] sinh
- [ ] sinhf
- [x] sinpi
- [x] sinpif
- [x] spence
- [x] spencef
- [x] sqrt
- [x] sqrt1pm1
- [ ] sqrt1pm1f
- [x] sqrtf
- [x] sqrtpi
- [x] sqrtpif
- [x] tan
- [x] tanf
- [x] tand
- [x] tandf
- [x] tanh
- [ ] tanhf
- [x] tribonacci
- [x] tribonaccif
- [x] trigamma
- [x] trigammaf
- [x] trunc
- [x] trunc10
- [ ] trunc10f
- [x] trunc2
- [ ] trunc2f
- [x] truncb
- [ ] truncbf
- [x] truncf
- [x] truncn
- [ ] truncnf
- [x] truncsd
- [ ] truncsdf
- [x] vercos
- [x] vercosf
- [x] versin
- [x] versinf
- [x] wrap
- [x] wrapf
- [x] xlog1py
- [ ] xlog1pyf
- [x] xlogy
- [x] xlogyf

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Pratik772846** [comment]
@kgryte I would like to work on this.

**Comment by kgryte** [comment]
@Pratik772846 I suggest picking one of the associated RFCs for updating a single package. This is a tracking issue.

**Comment by kgryte** [comment]
@Pranavchiku As you've been managing a number of the RFCs and PRs, would you mind updating the OP to match the current state of implementations?

**Comment by Pranavchiku** [comment]
I am not sure if this can be closed now, reopening this.

**Comment by Planeshifter** [comment]
@Pranavchiku Yeah, I think GitHub unfortunately auto-closes it when we have a PR where the opening comment includes "Fixes #649" or something of the sort. Thanks for opening again!

But I see that I accidentally included "Closes #649" in the merge commit message. Will avoid and see whether that solves it going forward.

**Comment by Pranavchiku** [comment]
No worries, we can open it anytime so that is fine. Updated tracker to latest main.

Small script, not sure if it traps all cases. There can be false negatives but no false positives.

```shell
set -ex

# iterate over all folder in <.../math/base/special/*>
for d in <path>; do
  # if the folder is a directory
  if [ -d "$d" ]; then
	# get the name of the folder
	folder=$(basename $d)
	# check if it has `manifest.json` file
	if [ -f "$d/manifest.json" ]; then
		# if it has `manifest.json` file, then open it as j_, lookup js_[confs][dependencies] and see if it has "@stdlib/math/base/napi/unary"
		# if it has "@stdlib/math/base/napi/unary" then add it to the `names.md`
		jq -r '.jsdoc.confs.dependencies["@stdlib/math/base/napi/unary"]' $d/manifest.json
		if [ $? -eq 0 ]; then
			echo "- [x] $folder" >> names.md
		else
			echo "- [ ] $folder" >> names.md
		fi
	else
		echo "- [ ] $folder" >> names.md
	fi
  fi
done
```

**Comment by kgryte** [comment]
@Planeshifter You should always check the PR OP to ensure it properly links to issues and does not auto-close tracking issues. I often correct contributor PR OPs as they commonly include errors, including linking to incorrect issues or closing tracking issues.

**Comment by Pranavchiku** [comment]
Updated as per latest develop

**Comment by kgryte** [comment]
@gunjjoshi Would you mind updating the tracking issue with completed APIs? I believe `rempio2`, `csc`, and maybe others are finished.

**Comment by kgryte** [comment]
Would also be good to add relevant single-precision variants which have been, or still need to be, completed.

**Comment by gunjjoshi** [comment]
Yes @kgryte, I'll do that. But as this issue wasn't opened by me, I am unable to modify or edit this. Should I make a comment consisting of a list of the completed ones, and modifying that each time?

**Comment by gunjjoshi** [comment]
@kgryte The `C` implementations of the following functions have been done. They can be marked as completed now.

- cos
- cot
- coversin
- csc
- exp2
- fast
- fibonacci-index
- lcm
- log10
- negafibonacci
- rempio2
- round
- sin
- spence
- tan

**Comment by Planeshifter** [comment]
@gunjjoshi Marked as completed. 🚀

**Comment by kgryte** [comment]
I updated the issue to include missing single-precision variants.

**Comment by gunjjoshi** [comment]
The following single-precision variants can also be marked as completed.

- acosf
- acotf
- acscf
- acscdf
- asecdf
- asecf
- asindf
- atanf
- lnf
- rad2degf
- rcbrtf

**Comment by kgryte** [comment]
@gunjjoshi Updated!

**Comment by kgryte** [comment]
@gunjjoshi Looks like the tracking issue is missing `nanmin` and `nanmax`. There may be others which are missing.

**Comment by gunjjoshi** [comment]
> [@gunjjoshi](https://github.com/gunjjoshi) Looks like the tracking issue is missing `nanmin` and `nanmax`. There may be others which are missing.

Added `nanmin`, `nanmax` and `sec`, along with their single-precision equivalents.

**Comment by gunjjoshi** [comment]
@Planeshifter It seems that this issue got closed automatically due to the `Resolves #649` in #3076.

**Comment by Harsh-Mathur-1503** [comment]
@gunjjoshi Is this issue still open to work on ?

**Comment by gunjjoshi** [comment]
> [@gunjjoshi](https://github.com/gunjjoshi) Is this issue still open to work on ?

Yes, feel free to work on any of the packages which are unchecked, from the list.

**Comment by kgryte** [comment]
@anandkaranubc Would you be willing to update the tracking issue list and check off those packages which have already been added/completed? Seems like it could be out-of-date atm, and we've been getting some duplicate PRs for existing functionality.

**Comment by Girish-Garg** [comment]
I’d like to work on some of the tasks mentioned here. Can someone guide me on how to get started? like to know:
Where should I add the C implementations?
existing implementations I can refer to?
What important details should I keep in mind while working on this task?
Any other guidance would also be helpful.

**Comment by anandkaranubc** [comment]
**To be unchecked:**
- `cabs2f`
- `cabsf`
- `cceilf`
- `cflipsignf`
- `cidentityf`

**To be checked:**
- `atandf`
- `ceilsd`
- `cfloorf`
- `cosm1`
- `croundf`
- `falling-factorial`
- `negalucasf`
- `negafibonaccif`
- `riemann-zeta`
- `xlogyf`

**To be modified (if "really" necessary):**  
- `kernel-sinf` -> `kernel-sindf`
- `kernel-cosf` -> `kernel-cosdf`
- `kernel-tanf` -> `kernel-tandf`

**To be updated:**  
- `rempio2f` (removing the `?`)

**To be added:**
- `sindf`
- `cosdf`
- `tandf`
- `cscdf`
- `secdf`
- `cotdf`
- `sincosdf`

cc: @kgryte

**Comment by anandkaranubc** [comment]
> Can someone guide me on how to get started?

@Girish-Garg, it would be a good idea to review the merged PRs for the packages that have already been checked above to get a good understanding. All of them (preferably the recent ones) serve as equally good reference PRs. Once you have a clear idea, you can start working on new implementations, (ideally) beginning with some standalone packages. You can get an initial understanding from the "Implementation Blueprint" in this [issue](https://github.com/stdlib-js/google-summer-of-code/issues/106).

Also, be mindful to avoid creating duplicate PRs for packages that already have open PRs.

**Comment by Girish-Garg** [comment]
@anandkaranubc, I noticed that the single-precision hyperbolic sine function `sinhf` lacks both JS and C implementations so....I  have to build it from scratch or just create a wrapper over the existing `sinh` function to convert results to 32-bit precision?

**Comment by sahil20021008** [comment]
Hi, 
I would like to work on some of the tasks mentioned above. 
Will be starting with ceil10f to start with.
Any guidance would be helpful

**Comment by Girish-Garg** [comment]
@kgryte @anandkaranubc i was working on `kernel-sinf` js and c implementation and came across that all test cases of c is skipping 

![Image](https://github.com/user-attachments/assets/450fc019-f753-41c0-a0e3-584ffdded508)

To troubleshoot, I added some try-catch blocks to check if `native.js` is being properly imported. I discovered that the issue lies with `addon.js`, which is failing to import `addon.node`. The problem seems to be caused by the `#include "stdlib/math/base/napi/binary.h"` in `addon.c`, which is not being imported properly and is throwing an error.

How should I proceed to resolve this issue?

**Comment by anandkaranubc** [comment]
> Will be starting with ceil10f to start with.

`ceil10f` likely requires `powf` and `log10f` to be implemented first. Be careful about not choosing the implementations that are dependent on unimplemented functions.

**Comment by anandkaranubc** [comment]
> How should I proceed to resolve this issue?

Could we sync about this in the Gitter channel? Just tag me there in your message.

**Comment by Deepak91168** [comment]
C implementation is [`sec`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/sec/src) is present but still un-ticked.
Is it for serving some other purpose?

**Comment by gunjjoshi** [comment]
Thanks for pointing it out, @Deepak91168 . The issue would need to be updated based on the current status of the implementations.

cc: @anandkaranubc

**Comment by anandkaranubc** [comment]
Thanks @Deepak91168 and @gunjjoshi for the follow-up. The issue has been updated 🙂

**Comment by anandkaranubc** [comment]
Now that `powf` is merged, in case somebody wants to know which packages depend on `powf`, here is the list:

<img width="353" height="560" alt="Image" src="https://github.com/user-attachments/assets/83d7557d-de37-4304-9100-b944c8419f89" />

<img width="371" height="560" alt="Image" src="https://github.com/user-attachments/assets/6ba0b8cf-334f-40c6-ac66-dcefc0d49c8b" />

**Comment by aryan7071** [comment]
hey @kgryte  i was working on  math/base/special/round10f but when am committing  am facing an editorconfig lint error tried solving it from past two days but i couldn't , can u please guide me on this

**Comment by anandkaranubc** [comment]
@aryan7071 Sure. I don't see a PR open for that. Mind sending the screenshots in the Gitter group chat please? Thanks!

**Comment by aryan7071** [comment]
@anandkaranubc, I have uploaded a screenshot of the error. Please check it.
